set_property IOSTANDARD LVCMOS33 [get_ports in_clock_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports in_reset]
set_property IOSTANDARD LVCMOS33 [get_ports in_serial_data]
set_property IOSTANDARD LVCMOS33 [get_ports out_serial_data]
set_property PACKAGE_PIN W5 [get_ports in_clock_100MHz]
set_property PACKAGE_PIN T18 [get_ports in_reset]
set_property PACKAGE_PIN J1 [get_ports out_serial_data]
set_property PACKAGE_PIN L2 [get_ports in_serial_data]
